"""Create medical_cost and medical_cost_file tables

Revision ID: 30e357373cbb
Revises: 
Create Date: 2024-07-26 16:42:13.071073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30e357373cbb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    create table resources (
        id varchar(255) primary key,
        cpu_cores int not null,
        memory numeric(5, 2) not null,
        storage numeric(7, 2) not null,
        network_bandwidth numeric(7, 2) not null,
        energy_consumption numeric(7, 2) not null,
        status varchar(50) not null,
    )
    ''')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('drop table resources')
    # ### end Alembic commands ###
